apps/instruments/urls.py
from django.urls import path, re_path

from . import views


app_name = 'instruments'
urlpatterns = [
    re_path('(?P<instrument_id>\d+)', views.individual_display, name="individual_display"),
]

apps/performances/urls.py
from django.urls import path, re_path
from . import views

app_name = 'performances'

urlpatterns = [ 
	path('add/', views.add, name="add"),
	path('upcoming/', views.upcoming, name="upcoming"),
	# Note: upcoming will evetually need an re_path
]

# urls to add:
# views.individual

apps/users/urls.py
from django.urls import path, re_path

from .  import views


app_name = 'users'
urlpatterns = [
    path('login_handler/', views.login_handler, name="login_handler"),
    path('logout_handler/', views.logout_handler, name='logout_handler'),
    path('register_coach/', views.register_coach, name="coach_registration_handler"),
    path('register_member/', views.register_member, name="member_registration_handler"),
    path('register_patron/', views.register_patron, name="patron_registration_handler"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('get-reset-token/', views.get_reset_token, name='get_reset_token'),
    path('reset-handler/', views.reset_token_handler, name='reset_token_handler'),


    re_path('edit/(?P<member_id>\d+)/', views.edit_member, name='edit_member'),
    re_path('(?P<member_id>\d+)/', views.individual_member, name="individual_member"),
]

chambernet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls')),
    path('users/', include('apps.users.urls')),
    path('instruments/', include('apps.instruments.urls')),
    path('performances/', include('apps.performances.urls')),
]

apps/performances/views.py
from django.shortcuts import render
from ..instruments.models import Instrument
# from .models import Performance

# Create your views here.

def add(req):

	context = {
		'instruments' : Instrument.objects.all()
	}

	return render(req, 'html/add.html', context)

def upcoming(req):

	context = {
		'instruments' : Instrument.objects.all(),
	}

	return render(req, 'html/upcoming.html', context)

apps/performances/templates/html/add.html
{% extends 'performances_base.html' %}
{% load static %}

{#
    instruments = list of all instruments.
#}

<!-- Load CSS (different for each template): -->
{% block load_css %}
    <link rel="stylesheet" type="text/css" href='{% static "css/add.css" %}'>
{% endblock %}

{% block header %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark navbar-custom">

    <!-- Logo -->
    <!-- If using brand link: -->
    <!-- <a class="navbar-brand brand" href="{% url 'public:welcome' %}">Houston Chamber Music Network</a> -->

    <!-- If no link: -->
    <h5 class="brand">Houston Chamber Music Network</h5>
    

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar links -->
        <ul class="navbar-nav mr-4">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:dashboard' %}">DASHBOARD</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:upcoming' %}">UPCOMING PERFORMANCES</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'performances:add' %}">ADD PERFORMANCE</a>
            </li>
            <!-- Instruments dropdown: -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle scrollable-menu" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FIND PLAYERS</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for instrument in instruments %}
                        <a href="{% url 'instruments:individual_display' instrument.id %}" class="dropdown-item"> {{ instrument.name }} </a>
                    {% endfor %}
                </div>
            </li>
        </ul>

        <!-- Navbar right -->
        <ul class="navbar-nav ml-auto">
            <!-- Link to external login: -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_handler' %}">LOGOUT</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block main_content %}
<header class="main">
    <div class="container">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <h1>Add Performances feature is coming soon!</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

apps/performances/templates/html/upcoming.html
{% extends 'performances_base.html' %}
{% load static %}

{#
    instruments = list of all instruments.
#}

<!-- Load CSS (different for each template): -->
{% block load_css %}
    <link rel="stylesheet" type="text/css" href='{% static "css/upcoming.css" %}'>
{% endblock %}
</head>


{% block header %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark navbar-custom">

    <!-- Logo -->
    <!-- If using brand link: -->
    <!-- <a class="navbar-brand brand" href="{% url 'public:welcome' %}">Houston Chamber Music Network</a> -->

    <!-- If no link: -->
    <h5 class="brand">Houston Chamber Music Network</h5>
    

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar links -->
        <ul class="navbar-nav mr-4">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:dashboard' %}">DASHBOARD</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'performances:upcoming' %}">UPCOMING PERFORMANCES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:add' %}">ADD PERFORMANCE</a>
            </li>
            <!-- Instruments dropdown: -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle scrollable-menu" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FIND PLAYERS</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for instrument in instruments %}
                        <a href="{% url 'instruments:individual_display' instrument.id %}" class="dropdown-item"> {{ instrument.name }} </a>
                    {% endfor %}
                </div>
            </li>
        </ul>

        <!-- Navbar right -->
        <ul class="navbar-nav ml-auto">
            <!-- Link to external login: -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_handler' %}">LOGOUT</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}
    	
{% block main_content %}
<header class="main">
    <div class="container">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <h1>Upcoming Performances feature is coming soon!</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}