apps/instruments/urls.py
from django.urls import path, re_path

from . import views


app_name = 'instruments'
urlpatterns = [
    re_path('(?P<instrument_id>\d+)', views.individual_display, name="individual_display"),
]

apps/performances/urls.py
from django.urls import path, re_path
from . import views

app_name = 'performances'

urlpatterns = [ 
	path('add/', views.add, name="add"),
	path('upcoming/', views.upcoming, name="upcoming"),
	# Note: upcoming will evetually need an re_path
]

# urls to add:
# views.individual

apps/users/urls.py
from django.urls import path, re_path

from .  import views


app_name = 'users'
urlpatterns = [
    path('login_handler/', views.login_handler, name="login_handler"),
    path('logout_handler/', views.logout_handler, name='logout_handler'),
    path('register_coach/', views.register_coach, name="coach_registration_handler"),
    path('register_member/', views.register_member, name="member_registration_handler"),
    path('register_patron/', views.register_patron, name="patron_registration_handler"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('get-reset-token/', views.get_reset_token, name='get_reset_token'),
    path('reset-handler/', views.reset_token_handler, name='reset_token_handler'),


    re_path('edit/(?P<member_id>\d+)/', views.edit_member, name='edit_member'),
    re_path('(?P<member_id>\d+)/', views.individual_member, name="individual_member"),
]

chambernet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls')),
    path('users/', include('apps.users.urls')),
    path('instruments/', include('apps.instruments.urls')),
    path('performances/', include('apps.performances.urls')),
]

apps/instruments/models.py
from django.db import models


class Instrument(models.Model):

    name = models.TextField()


    def __str__(self):
        return self.name

apps/instruments/views.py
from django.shortcuts import redirect, render

from .models import Instrument
from ..users.models import Member


def individual_display(req, instrument_id):

    if 'uid' not in req.session:
        return redirect('public:welcome')

    if not Instrument.objects.filter(id=instrument_id).exists():
        return redirect('users:dashboard')

    this_instrument = Instrument.objects.get(id=instrument_id)
    context = {
        'all_instruments' : Instrument.objects.all(),
        'instrument' : this_instrument,
        'primary_users' : Member.objects.filter(primary_instrument__pk=instrument_id),
        'secondary_users' : Member.objects.filter(secondary_instrument__pk=instrument_id),
    }

    return render(req, 'html/individual_instrument.html', context)

apps/instruments/templates/html/individual_instrument.html
<!-- {# 
    instrument = this particular instrument 
#}

{# 
	members = members affiliated with this instrument 
#}

{#
	all_instruments = list of all instruments (for navbar)
#} -->

<!DOCTYPE html>
<html>
    <head>
        <title>HCMN : {{ page_name }}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Load CSNs (same for all templates): -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

        <!-- Google fonts: -->
        <link href="https://fonts.googleapis.com/css?family=Arimo|Fira+Sans|Lato|Lora|Mukta|Noto+Serif|Oxygen|Roboto|Rubik" rel="stylesheet">

        <!-- css file: -->
        {% load static %}
        <link rel="stylesheet" type="text/css" href='{% static "css/individual_instrument.css" %}'>
    </head>
 
    <body>
        <nav class="navbar navbar-expand-md fixed-top navbar-dark navbar-custom">

            <!-- Logo -->
            <!-- If using brand link: -->
            <!-- <a class="navbar-brand brand" href="{% url 'public:welcome' %}">Houston Chamber Music Network</a> -->

            <!-- If no link: -->
            <h5 class="brand">Houston Chamber Music Network</h5>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Navbar links -->
                <ul class="navbar-nav mr-4">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}">DASHBOARD</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'performances:upcoming' %}">UPCOMING PERFORMANCES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'performances:add' %}">ADD PERFORMANCE</a>
                    </li>
                    <!-- Instruments dropdown: -->
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle scrollable-menu" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FIND PLAYERS</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for instrument in all_instruments %}
                                <a href="{% url 'instruments:individual_display' instrument.id %}" class="dropdown-item"> {{ instrument.name }} </a>
                            {% endfor %}
                        </div>
                    </li>
                </ul>

                <!-- Navbar right -->
                <ul class="navbar-nav ml-auto">
                    <!-- Link to external login: -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout_handler' %}">LOGOUT</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main content: -->
        <div class="container-fluid" id="main-container">

            <!-- Primary instrument table: -->
                <div class="card">
                    <div class="card-header bg-transparent">
                        <h4>Members who list {{ instrument.name }} as their primary instrument:</h4>
                    </div>

                    <div class="card-body">
                        {% if not primary_users %}
                        <h5>There are currently no members who list {{ instrument.name }} as their primary instrument.</h5>

                        {% else %}
                            
                            <div class="table-responsive">
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>HCMN Rating</th>
                                            <th>Email</th>
                                            <th>Location</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for member in primary_users %}
                                        <tr>
                                            <td><a href="{% url 'users:individual_member' member.id %}">{{ member.first_name }} {{ member.last_name }}</a></td>
                                            <td>{{ member.get_rating_display }}</td>
                                            <td>{{ member.email }}</td>
                                            <td>{{ member.area }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endif %}
                    </div>
                </div>

            <div class="card">
                <div class="card-header bg-transparent">
                    <h4>Members who list {{ instrument.name }} as their secondary instrument:</h4>
                </div>

                <div class="card-body">
                    {% if not secondary_users %}
                    <h5>There are currently no members who list {{ instrument.name }} as their secondary instrument.</h5>

                    {% else %}
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>HCMN Rating</th>
                                        <th>Email</th>
                                        <th>Location</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for member in secondary_users %}
                                    <tr>
                                        <td><a href="{% url 'users:individual_member' member.id %}">{{ member.first_name }} {{ member.last_name }}</a></td>
                                        <td>{{ member.get_rating_display }}</td>
                                        <td>{{ member.email }}</td>
                                        <td>{{ member.area }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% endif %}
                <!-- End card-body: -->
                </div>
            <!-- End card: -->
            </div>
        <!-- End main container: -->
        </div>
        
        <!-- Footer: -->
        <footer class="pt-0">
            <div class="container-fluid footer-container text-center text-md-left">
                <div class="row">
                    <div class="col-md-9 mt-md-0 mt-3">
                        <ul class="footer-links list-unstyled">
                            <li>
                                <a href="{% url 'public:about' %}"><h5>ABOUT US</h5></a>
                            </li>
                            <li>
                                <a href="{% url 'public:resources' %}"><h5>RESOURCES</h5></a>
                            </li>
                            <li>
                                <a href="{% url 'public:sponsors' %}"><h5>SPONSORS</h5></a>
                            </li>
                        </ul>
                    </div>

                    <hr class="clearfix w-100 d-md-none pb-0">

                    <div class="col-md-3 mb-md-0 mb-3" id="contact">
                        <h5><strong>CONTACT EMAIL:</strong></h5>
                        <p>michael@houstonchambermusic.org</p><br>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center py-2">Web Design ©2019 Ad Astra Web Services</div>
        </footer>
    </body>
</html>