apps/instruments/urls.py
from django.urls import path, re_path

from . import views


app_name = 'instruments'
urlpatterns = [
    re_path('(?P<instrument_id>\d+)', views.individual_display, name="individual_display"),
]

apps/performances/urls.py
from django.urls import path, re_path
from . import views

app_name = 'performances'

urlpatterns = [ 
	path('add/', views.add, name="add"),
	path('upcoming/', views.upcoming, name="upcoming"),
	# Note: upcoming will evetually need an re_path
]

# urls to add:
# views.individual

apps/users/urls.py
from django.urls import path, re_path

from .  import views


app_name = 'users'
urlpatterns = [
    path('login_handler/', views.login_handler, name="login_handler"),
    path('logout_handler/', views.logout_handler, name='logout_handler'),
    path('register_coach/', views.register_coach, name="coach_registration_handler"),
    path('register_member/', views.register_member, name="member_registration_handler"),
    path('register_patron/', views.register_patron, name="patron_registration_handler"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('get-reset-token/', views.get_reset_token, name='get_reset_token'),
    path('reset-handler/', views.reset_token_handler, name='reset_token_handler'),


    re_path('edit/(?P<member_id>\d+)/', views.edit_member, name='edit_member'),
    re_path('(?P<member_id>\d+)/', views.individual_member, name="individual_member"),
]

chambernet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls')),
    path('users/', include('apps.users.urls')),
    path('instruments/', include('apps.instruments.urls')),
    path('performances/', include('apps.performances.urls')),
]

apps/users/models.py
from __future__ import unicode_literals
import re

from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.models import User
from django.db import models
from django.forms.models import model_to_dict

from ..emails.models import Email
from ..instruments.models import Instrument


NAME_REGEX = re.compile(r"^[a-zA-Z]+(?:[-\s.]+[a-zA-Z]+)*$")
EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")


class MemberManager(models.Manager):


    def member_update(self, update_dict):
        update_dict['phone_number'] = update_dict.pop('tel1') + update_dict.pop('tel2') + update_dict.pop('tel3')
        user_id = update_dict.pop('id')
        pw = update_dict.pop('password')
        
        self.filter(pk=user_id).update(**update_dict) 
        
        user = self.get(pk=user_id)
        user.password = make_password(pw)
        user.save()


    def validate_edit(self, user_id, data):
        # The idea here is to use dicts to compare the changes, and then use our member validation to validate the fields.

        orig = model_to_dict(self.get(id=user_id))
        modded = False

        # Hard copy
        data = data.copy()

        # Remove CSRF token.
        data.pop('csrfmiddlewaretoken')

        # Unfortunately, this is really the only way to do this.
        data['phone_number'] = data.pop('tel1') + data.pop('tel2') + data.pop('tel3')
        if not data['phone_number'][0]:
            data['phone_number'][0] = orig['phone_number'][0:3]
        if not data['phone_number'][1]:
            data['phone_number'][1] = orig['phone_number'][3:6]
        if not data['phone_number'][2]:
            data['phone_number'][2] = orig['phone_number'][6:10]
        data['phone_number'] = ''.join(data['phone_number'])

        # Normalize foreign keys (primary_instrument and secondary_instrument)
        data['primary_instrument'] = int(data['primary_instrument'])
        if not data['secondary_instrument']:
            data['secondary_instrument'] = None

        # Do a password validation if they've entered a PW to change.  If not, just pop both PW-keys.
        if data['new_password'] or data['confirm_password']:
            errors = self.validate_password(data['new_password'], data['confirm_password'])
            print(data['new_password'])
            if errors:
                return errors, orig
            else:
                pw = data['new_password']
                data.pop('new_password')
                data.pop('confirm_password')
                data['password'] = pw
        else:
            data.pop('new_password')
            data.pop('confirm_password')

        for key in data:
            # Explicit check against empty string.
            if data[key] != '' and orig[key] != data[key]:
                print('WORKING, DIFF FOUND', key)
                orig[key] = data[key]
                print(orig[key])
                modded = True

        if modded:
            phone_number = orig.pop('phone_number')
            orig['tel1'] = phone_number[0:3]
            orig['tel2'] = phone_number[3:6]
            orig['tel3'] = phone_number[6:10]
            errors = self.new_member_validation(orig)
            expected_error = {'email' : 'Email already found in database. Either enter a different email or go to sign in page.'}
            if errors != expected_error:
                errors.pop('email')
                return errors, orig



        return None, orig


    def validate_login(self, data):
        email = data['email'].lower()
        attempted_password = data['password']

        user = None
        errors = {}

        if self.filter(email=email).exists():
            user = self.get(email=email)
            if not check_password(attempted_password, user.password):
                print('Working')
                errors['password'] = 'Username/Password combination not found, please try again or use the "Forgot Password" button below.'
        else:
            errors['password'] = 'Username/Password combination not found, please try again or use the "Forgot Password" button below.'

        return user, errors


    def new_member_validation(self, post_data, is_coach=False):
        errors = {}

        first_name = post_data['first_name']
        last_name = post_data['last_name']
        email = post_data['email'].lower()
        street_address = post_data['street_address']
        unit_number = post_data['unit_number']
        city = post_data['city']
        state = post_data['state']
        zip_code = post_data['zip_code']
        phone_number = post_data['tel1'] + post_data['tel2'] + post_data['tel3']
        bio = post_data['bio']
        area = post_data['area']

        if len(first_name) < 2:
            errors['first_name'] = 'First name must contain at least two characters.'
        elif not NAME_REGEX.match(first_name):
            errors['first_name'] = 'First name contains an invalid character.'

        if len(last_name) < 2:
            errors['last_name'] = 'Last name must contain at least two characters.'
        elif not NAME_REGEX.match(last_name):
            errors['last_name'] = 'Last name contains an invalid character.'

        if not EMAIL_REGEX.match(email):
            errors['email'] = 'Please enter a valid email address.'
        elif self.member_email_exists(email):
            errors['email'] = 'Email already found in database. Either enter a different email or go to sign in page.'

        if len(street_address) < 1:
            errors['street_address'] = 'Please enter your street address.'

        if len(city) < 1:
            errors['city'] = 'Please enter a city.'

        if len(zip_code) != 5:
            errors['zip_code'] = 'Please enter a valid US zip code.'

        if len(phone_number) != 10:
            errors['phone_number'] = 'Please enter a valid US phone number.'

        if 'primary_instrument' not in post_data:
            errors['primary_instrument'] = 'Please select a primary instrument.'

        if len(bio) < 1:
            errors['bio'] = 'Please provide a brief musical bio.'

        if len(area) < 10:
            errors['area'] = 'Please provide area information (Minimum of 10 characters).'

        if (not is_coach) and 'rating' not in post_data:
            errors['rating'] = 'Please select a skill rating.'

        return errors


    def add_member(self, post_data, is_coach=False):
        first_name = post_data['first_name']
        last_name = post_data['last_name']
        email = post_data['email'].lower()
        street_address = post_data['street_address']
        unit_number = post_data['unit_number']
        city = post_data['city']
        state = post_data['state']
        zip_code = post_data['zip_code']
        area = post_data['area']
        phone_number = post_data['tel1'] + post_data['tel2'] + post_data['tel3']
        primary_instrument = Instrument.objects.get(pk=post_data['primary_instrument'])

        if ('secondary_instrument' in post_data) and (post_data['secondary_instrument'] != 'None'):
            secondary_instrument = Instrument.objects.get(pk=post_data['secondary_instrument'])
        else:
            secondary_instrument = None

        bio = post_data['bio']
        # Make this a choiceField later.
        if is_coach:
            rating = Member.PROFESSIONAL
        else:
            rating = post_data['rating']

        default_password = self.generate_new_password()
        self.create(
                            first_name=first_name,
                            last_name=last_name,
                            email=email,
                            street_address=street_address,
                            unit_number=unit_number,
                            city=city,
                            state=state, 
                            zip_code=zip_code,
                            area=area,
                            phone_number=phone_number,
                            password=make_password(default_password),
                            primary_instrument=primary_instrument,
                            secondary_instrument=secondary_instrument,
                            bio=bio,
                            rating=rating,
                            is_coach=is_coach)

        return email, default_password


    def member_email_exists(self, email):
        return self.filter(email=email.lower()).exists()


    def generate_new_password(self):
        new_password = User.objects.make_random_password(length=14, allowed_chars="abcdefghjkmnpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567889")

        while self.validate_password(new_password, new_password):
            new_password = User.objects.make_random_password(length=14, allowed_chars="abcdefghjkmnpqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567889")

        return new_password


    def get_all_with_instrument(self, instrument):
        return self.filter(models.Q(primary_instrument=instrument) | models.Q(secondary_instrument=instrument))


    def validate_password(self, password, confirm_password):
        errors = []

        if password != confirm_password:
            errors.append('Your passwords do not match eachother.')

        if len(password) < 8:
            errors.append('Your password must contain atleast eight characters.')

        if all(True if not char.isdigit() else False for char in password):
            errors.append('Your password must contain atleast one digit.')

        return errors


    def set_new_password(self, user_id, new_password):
        user = self.get(id=user_id)
        user.password = make_password(new_password)

        user.save()


class PatronManager(models.Manager):
    def new_patron_validation(self, post_data):
        first_name = post_data['first_name']
        last_name = post_data['last_name']
        email = post_data['email']
        street_address = post_data['street_address']

apps/users/views.py
from django.shortcuts import redirect, render

from ..emails.models import Email
from ..instruments.models import Instrument
from .models import Member, Patron, ResetToken


def login_handler(req):

    if req.method == "POST":
        user, errors = Member.objects.validate_login(req.POST)
        if not errors:
            req.session['uid'] = user.pk
            return redirect('users:dashboard')
        else:
            req.session['errors'] = errors
            print(errors)
            req.session['old_data'] = {
                                        'email' : req.POST['email'],
                                      }

    return redirect('public:login')


# houstonchambermusic.org/register_coach/
def register_coach(req):
    if req.method == "POST":
        errors = Member.objects.new_member_validation(req.POST, is_coach=True)

        if not errors:
            email, password = Member.objects.add_member(req.POST, is_coach=True)
            Email.objects.send_new_registration(email, password, is_coach=True)
            return redirect('public:success')
        else:
            req.session['errors'] = errors
            req.session['old_data'] = req.POST

    return redirect('public:new_coach')


# houstonchambermusic.org/register_member/
def register_member(req):
    if req.method == "POST":
        errors = Member.objects.new_member_validation(req.POST)

        if not errors:
            email, password = Member.objects.add_member(req.POST)
            Email.objects.send_new_registration(email, password)
            return redirect('public:success')
        else:
            req.session['errors'] = errors
            req.session['old_data'] = req.POST

    return redirect('public:new_member')


# houstonchambermusic.org/register_patron/
def register_patron(req):
    if req.method == "POST":
        errors = Patron.objects.new_patron_validation(req.POST)

        if not errors:
            Patron.objects.add_patron(req.POST)
            return redirect('public:success')
        else:
            req.session['errors'] = errors
            req.session['old_data'] = req.POST

    return redirect('public:new_patron')


def dashboard(req):

    if 'uid' not in req.session:
        return redirect('public:welcome')

    context = {
        'page_name' : 'Member Dashboard',
        'user' : Member.objects.get(id=req.session['uid']),
        'instruments' : Instrument.objects.all(),
    }

    return render(req, 'html/dashboard.html', context)


def individual_member(req, member_id):

    if ('uid' not in req.session) or (not Member.objects.filter(id=member_id).exists()):
        return redirect('public:welcome')

    context = {
        'page_name' : 'Member page',
        'member' : Member.objects.get(id=member_id),
        'instruments' : Instrument.objects.all(),
    }

    return render(req, 'html/individual_member.html', context)


def edit_member(req, member_id):

    if 'uid' not in req.session:
        return redirect('public:welcome')

    if req.method == 'POST':
        errors, update = Member.objects.validate_edit(req.session['uid'], req.POST)
        if not errors:
            Member.objects.member_update(update)
            return redirect('users:dashboard')

    if int(member_id) != req.session['uid']:
        return redirect('users:dashboard')
    else:
        context = {
            'page_name' : 'Edit information',
            'user' : Member.objects.get(id=req.session['uid']),
            'instruments' : Instrument.objects.all(),
        }
        return render(req, 'html/edit_member.html', context)


def get_reset_token(req):
    if req.method == 'POST':
        token = ResetToken.objects.generate_new_token(req.POST['email'])
        if token:
            Email.objects.send_pw_reset_link(req.POST['email'], token.value)
            print("WORKING: {}".format(token.value))

    return redirect('public:reset_sent')

def reset_token_handler(req):
    if req.method == 'POST':
        token = ResetToken.objects.get(value=req.POST['token'])
        user = token.user

        errors = Member.objects.validate_password(req.POST['new_password'], req.POST['confirm_password'])
        if not errors:
            Member.objects.set_new_password(user.id, req.POST['new_password'])
            token.delete()
            return redirect('public:new_pw_success')
        else:
            req.session['errors'] = {
                'password' : errors,
            }
            return redirect('public:pw_reset_display', req.POST['token'])

    return redirect('public:welcome')


def logout_handler(req):
    req.session.pop('uid', None)

    return redirect('public:welcome')

apps/users/templates/html/dashboard.html
{% extends 'users_base.html' %}
{% load static %}

{#
user = Member object that is currently logged in (with all attributes).
#}

{# 
    instruments = list of all instruments. 
#}

{% block load_css %}
    <link rel="stylesheet" type="text/css" href='{% static "css/dashboard.css" %}'>
{% endblock %}

{% block header %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark navbar-custom">

    <!-- Logo -->
    <!-- If using brand link: -->
    <!-- <a class="navbar-brand brand" href="{% url 'public:welcome' %}">Houston Chamber Music Network</a> -->

    <!-- If no link: -->
    <h5 class="brand">Houston Chamber Music Network</h5>
    

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar links -->
        <ul class="navbar-nav mr-4">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:dashboard' %}">DASHBOARD</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:upcoming' %}">UPCOMING PERFORMANCES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:add' %}">ADD PERFORMANCE</a>
            </li>
            <!-- Instruments dropdown: -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle scrollable-menu" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FIND PLAYERS</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for instrument in instruments %}
                        <a href="{% url 'instruments:individual_display' instrument.id %}" class="dropdown-item"> {{ instrument.name }} </a>
                    {% endfor %}
                </div>
            </li>
        </ul>

        <!-- Navbar right -->
        <ul class="navbar-nav ml-auto">
            <!-- Link to external login: -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_handler' %}">LOGOUT</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block main_content %}
<!-- Div for card deck: -->
<div class="card-deck py-3 px-5">
    <!-- Information card: -->
    <div class="card">

        <!-- Card-header: -->
        <div class="card-header bg-transparent">
            <h4>Your Information</h4>
        </div>

        <!-- Card-body: -->
        <div class="card-body">
            <div class="card-text py-5">
                <dl class="row">
                    <dt class="col-sm-5">Name</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.first_name }} {{ user.last_name }}</p>
                    </dd>

                    <dt class="col-sm-5">Email</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.email }}</p>
                    </dd>

                    <dt class="col-sm-5">Phone</dt>
                    <dd class="col-sm-7">
                        <p>({{ user.phone_number|slice:"0:3" }}) {{ user.phone_number|slice:"3:6" }}-{{ user.phone_number|slice:"6:10" }}</p>
                    </dd>

                    <dt class="col-sm-5">Address</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.street_address }}</p>
                        <p>{{ user.city }}, {{ user.state }}</p>
                        <p>{{ user.zip_code }}</p>
                    </dd>

                    <dt class="col-sm-5">Primary instrument</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.primary_instrument }}</p>
                    </dd>

                    <dt class="col-sm-5">Second instrument</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.secondary_instrument }}</p>
                    </dd>

                    <dt class="col-sm-5">Location</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.area }}</p>
                    </dd>

                    <dt class="col-sm-5">HCMN Rating</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.get_rating_display }}</p>
                    </dd>

                    <dt class="col-sm-5">Bio</dt>
                    <dd class="col-sm-7">
                        <p>{{ user.bio }}</p>
                    </dd>
                </dl>
            </div>
        <!-- End div for card-body: -->
        </div>

        <!-- Card-footer: -->
        <div class="card-footer bg-transparent">
            <a href="{% url 'users:edit_member' user.id %}" class="btn btn-reg btn-info btn-block">EDIT INFORMATION</a>
        </div>
    <!-- End div for information card: -->
    </div>

    <!-- Performances card: -->
    <div class="card">
        <div class="card-header bg-transparent">
            <h4>Your performances</h4>
        </div>

        <div class="card-body">
            <div class="card-text text-center mt-3 py-5">
                <h5 class="pb-4">Add performance feature is coming soon.</h5>
            </div>
        </div>

        <div class="card-footer bg-transparent">
            <a href="{% url 'performances:add' %}" class="btn btn-reg btn-info btn-block">ADD PERFORMANCE</a>
        </div>
    <!-- End performance card: -->
    </div>

<!-- End card-deck: -->
</div> 
{% endblock %}

apps/users/templates/html/individual_member.html
{% extends 'users_base.html' %}
{% load static %}

{#
    user = Member object that is currently logged in (with all attributes).
#}

{#
    instruments = list of all instruments.
#}

{% block load_css %}
    <link rel="stylesheet" type="text/css" href='{% static "css/individual_member.css" %}'>
{% endblock %}

{% block header %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark navbar-custom">

    <!-- Logo -->
    <!-- If using brand link: -->
    <!-- <a class="navbar-brand brand" href="{% url 'public:welcome' %}">Houston Chamber Music Network</a> -->

    <!-- If no link: -->
    <h5 class="brand">Houston Chamber Music Network</h5>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Navbar links -->
        <ul class="navbar-nav mr-4">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:dashboard' %}">DASHBOARD</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:upcoming' %}">UPCOMING PERFORMANCES</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'performances:add' %}">ADD PERFORMANCE</a>
            </li>
            <!-- Instruments dropdown: -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle scrollable-menu" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FIND PLAYERS</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for instrument in instruments %}
                        <a href="{% url 'instruments:individual_display' instrument.id %}" class="dropdown-item"> {{ instrument.name }} </a>
                    {% endfor %}
                </div>
            </li>
        </ul>

        <!-- Navbar right -->
        <ul class="navbar-nav ml-auto">
            <!-- Link to external login: -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_handler' %}">LOGOUT</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

{% block main_content %}
 <!-- Div for main container: -->
 <div id="main-container">
    <!-- Div for card deck: -->
    <div class="card-deck py-3 px-5">
        <!-- Information card: -->
        <div class="card">

            <!-- Card-header: -->
            <div class="card-header bg-transparent">
                <h4>{{ member.first_name }}'s Information</h4>
            </div>

            <!-- Card-body: -->
            <div class="card-body">
                <div class="card-text py-5">
                    <dl class="row">
                        <dt class="col-sm-5">Name</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.first_name }} {{ member.last_name }}</p>
                        </dd>

                        <dt class="col-sm-5">Email</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.email }}</p>
                        </dd>

                        <dt class="col-sm-5">Primary instrument</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.primary_instrument }}</p>
                        </dd>

                        <dt class="col-sm-5">Second instrument</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.secondary_instrument }}</p>
                        </dd>

                        <dt class="col-sm-5">Location</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.area }}</p>
                        </dd>

                        <dt class="col-sm-5">HCMN Rating</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.get_rating_display }}</p>
                        </dd>

                        <dt class="col-sm-5">Bio</dt>
                        <dd class="col-sm-7">
                            <p>{{ member.bio }}</p>
                        </dd>
                    </dl>
                </div>
            <!-- End card-body: -->
            </div>
        <!-- End information card: -->
        </div>

        <!-- Performances card: -->
        <div class="card">
            <div class="card-header bg-transparent">
                <h4>{{ member.first_name }}'s Performances</h4>
            </div>

            <div class="card-body">
                <div class="card-text text-center mt-3 py-5">
                    <h5 class="pb-4">Add performance feature is coming soon.</h5>
                </div>
            </div>
        <!-- End performances card: -->
        </div>
    <!-- End card-deck: -->
    </div> 
</div>
{% endblock %}